from custom_exceptions import ArgumentException